version: "3.0"
services:
  main-service:
    build:
      context: ./main-service
    environment:
      - PORT=8080
      - DATABASE_HOST=127.0.0.1:5432
      - DATABASE_NAME=cities
      - DATABASE_USERNAME=fara0000
      - DATABASE_PASSWORD=SGJc3Jzi

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
#      depends_on:
#        - backend
  calculate-service-spring:
    build:
      context: calculate-service-2/spring
    environment:
      - PORT=8081
  calculate-service-ejb:
    build:
      context: calculate-service-2/EJB
    environment:
      - PORT=8082
  haproxy:
    image: "haproxy:2.2-alpine"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./cert.pem:/etc/ssl/certs/site.pem