version: "3.0"
services:
  main-service:
    build:
      context: ./main-service
    environment:
      - PORT=8080
      - DATABASE_HOST=127.0.0.1:5432
      - DATABASE_NAME=cities
      - DATABASE_USERNAME=fara0000
      - DATABASE_PASSWORD=SGJc3Jzi

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
  zuul:
    build:
      context: ./zuul
  eureka:
    build:
      context: ./eureka
#      depends_on:
#        - backend
#  calculate-service-spring:
#    build:
#      context: calculate-service-2/spring
#    environment:
#      - PORT=8081
#  haproxy:
#    image: "haproxy:2.2-alpine"
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  consul:
    image: bitnami/consul:1
    container_name: consul
    restart: always
    healthcheck:
      # return information about the status of the Consul cluster https://www.consul.io/api/status.html
      test: [ "CMD", "curl", "-X", "GET", "localhost:8500/v1/status/leader" ]
      interval: 1s
      timeout: 3s
      retries: 60
    volumes:
      - ./logs/consul_data:/bitnami
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'